### ISSUE TITLE
Bot replies to any "command-like" message in groups

### ISSUE THREAD

**Issue by fragel** [iclavijos/msdb-telegram-bot#1]
Buenas Ivan,

**Context:** The bot behaviour with command-like messages (`/XXXX`) is not ideal in groups where one may have other bots that of course have other `/commands` defined. 
**Issue:** Any `/command` is replied by the bot even if not addressed to it. 
**Description:** Even a command specifically addressed to another bot in the same group `/XXX@MyBot` will be replied complaining (con la coña del `error.wtf` ;-) ) by yours. I can see `error.wtf` is called in `processInvalidCommandUpdate`.

While I understand this behaviour suits a private chat with the bot, unfortunately in groups it is not possible while having other bots.

P.S.: I tried to find under which conditions you execute the `processInvalidCommandUpdate` function to propose something, but I cannot see it in the code. In any case, the bot should just check if the command is being addressed to itself and ignore all others.
I found a reference with a similar issue and a solution: [https://github.com/python-telegram-bot/python-telegram-bot/issues/319](https://github.com/python-telegram-bot/python-telegram-bot/issues/319).

Un saludo y ¡gracias por el bot!

**Comment by iclavijos** [comment]
Thanks for the feedback!

As this was my first ever bot, and I used more towards start coding in Kotlin, I really appreciate your feedback as I didn't think at all about the issue you describe. Let me have a look at it.

`processInvalidCommandUpdate` is triggered by parent class, which belongs to the Telegram library I used

PS: Also, let me push a few commits I still have in my local repo

**Comment by fragel** [comment]
Hi Ivan,

I tested the fix in a group. Still gets chatty throwing `error.wtf `for a message like /ceo@AnotherBot.
It is working when the message starts with another character than `/`.

Saludos,
Francisco

**Comment by iclavijos** [comment]
My fault... it's been a really hard week and I haven't uploaded it to the server yet :(

**Comment by iclavijos** [comment]
Have you tried it again?

**Comment by fragel** [comment]
Yes, I just tried. Still getting the message. This is from a group.

<img width="378" alt="Screenshot 2023-03-11 at 18 11 25" src="https://user-images.githubusercontent.com/5417164/224502437-3668533e-a747-42eb-be6f-e278031363eb.png">

**Comment by iclavijos** [comment]
Weird... I've been testing it and haven't been able to reproduce your error.

<img width="528" alt="image" src="https://user-images.githubusercontent.com/10941768/224504218-4c476f43-ee45-402b-9b0f-4dd610c6c3e0.png">

Will keep trying it and see if I find where's the error. In fact, with the current code, the error.wtf message is only triggered when the message is received in an individual chat, not in a group

https://github.com/iclavijos/msdb-telegram-bot/blob/1028066e96c88775a858289e38b19925eb6cb06e/src/main/kotlin/com/icesoft/msdb/telegram/bot/controllers/CommandsHandler.kt#L119

**Comment by iclavijos** [comment]
Finally found it... Telegram makes a distinction between "groups" and "super groups"
